name = "ca-phase-transition"
version = "0.1.0"
license = "MIT"
author = "Koe-eigh"
maintainer = "gongeizhitian@gmail.com"
copyright = "Copyright (c) 2026 Author. All Rights Reserved."

[features]
openmp.gfortran.flags = "-fopenmp"

[profiles]
default = ["openmp"]
